// @ts-check
import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';

export default defineConfig({
  site: (process.env.PUBLIC_SITE_URL || 'https://docnote.care').replace(/\/+$/, ''),
  trailingSlash: 'always',
  integrations: [tailwind()],
  i18n: {
    defaultLocale: 'en',
    locales: [
      'en',
      'zh',
      'es',
      'ar',
      'pt',
      'ja',
      'ru',
      'de',
      'fr',
      'ko',
      'it',
      'hi',
      'nl',
      'th',
      'sv',
      'no',
    ],
    routing: {
      prefixDefaultLocale: false,
    },
  },
  redirects: {
    '/en': '/',
    '/en/': '/',
    '/en/pricing/': '/pricing/',
    '/en/tutorial/': '/tutorial/',
    '/en/contact/': '/contact/',
    '/en/privacy/': '/privacy/',
    '/en/team/': '/team/',
    '/en/patient/': '/patient/',
    // Survey: EN + non-FR use /survey/; FR keeps /fr/sondage/
    '/sondage': '/survey/',
    '/sondage/': '/survey/',
    '/en/sondage/': '/survey/',
    '/en/survey/': '/survey/',
    '/fr/survey': '/fr/sondage/',
    '/fr/survey/': '/fr/sondage/',
    '/zh/sondage/': '/zh/survey/',
    '/es/sondage/': '/es/survey/',
    '/ar/sondage/': '/ar/survey/',
    '/pt/sondage/': '/pt/survey/',
    '/ja/sondage/': '/ja/survey/',
    '/ru/sondage/': '/ru/survey/',
    '/de/sondage/': '/de/survey/',
    '/ko/sondage/': '/ko/survey/',
    '/it/sondage/': '/it/survey/',
    '/hi/sondage/': '/hi/survey/',
    '/nl/sondage/': '/nl/survey/',
    '/th/sondage/': '/th/survey/',
    '/sv/sondage/': '/sv/survey/',
    '/no/sondage/': '/no/survey/',
    // Careers: EN + non-FR use /careers/; FR keeps /fr/emploi/
    '/emploi': '/careers/',
    '/emploi/': '/careers/',
    '/en/emploi/': '/careers/',
    '/en/careers/': '/careers/',
    '/fr/careers': '/fr/emploi/',
    '/fr/careers/': '/fr/emploi/',
    '/zh/emploi/': '/zh/careers/',
    '/es/emploi/': '/es/careers/',
    '/ar/emploi/': '/ar/careers/',
    '/pt/emploi/': '/pt/careers/',
    '/ja/emploi/': '/ja/careers/',
    '/ru/emploi/': '/ru/careers/',
    '/de/emploi/': '/de/careers/',
    '/ko/emploi/': '/ko/careers/',
    '/it/emploi/': '/it/careers/',
    '/hi/emploi/': '/hi/careers/',
    '/nl/emploi/': '/nl/careers/',
    '/th/emploi/': '/th/careers/',
    '/sv/emploi/': '/sv/careers/',
    '/no/emploi/': '/no/careers/',
    // Careers job pages (legacy emploi ↔ careers slug swap)
    '/emploi/digital-marketing-intern/': '/careers/digital-marketing-intern/',
    '/en/emploi/digital-marketing-intern/': '/careers/digital-marketing-intern/',
    '/en/careers/digital-marketing-intern/': '/careers/digital-marketing-intern/',
    '/fr/careers/digital-marketing-intern/': '/fr/emploi/digital-marketing-intern/',
    '/zh/emploi/digital-marketing-intern/': '/zh/careers/digital-marketing-intern/',
    '/es/emploi/digital-marketing-intern/': '/es/careers/digital-marketing-intern/',
    '/ar/emploi/digital-marketing-intern/': '/ar/careers/digital-marketing-intern/',
    '/pt/emploi/digital-marketing-intern/': '/pt/careers/digital-marketing-intern/',
    '/ja/emploi/digital-marketing-intern/': '/ja/careers/digital-marketing-intern/',
    '/ru/emploi/digital-marketing-intern/': '/ru/careers/digital-marketing-intern/',
    '/de/emploi/digital-marketing-intern/': '/de/careers/digital-marketing-intern/',
    '/ko/emploi/digital-marketing-intern/': '/ko/careers/digital-marketing-intern/',
    '/it/emploi/digital-marketing-intern/': '/it/careers/digital-marketing-intern/',
    '/hi/emploi/digital-marketing-intern/': '/hi/careers/digital-marketing-intern/',
    '/nl/emploi/digital-marketing-intern/': '/nl/careers/digital-marketing-intern/',
    '/th/emploi/digital-marketing-intern/': '/th/careers/digital-marketing-intern/',
    '/sv/emploi/digital-marketing-intern/': '/sv/careers/digital-marketing-intern/',
    '/no/emploi/digital-marketing-intern/': '/no/careers/digital-marketing-intern/',
    '/en/gtc/': '/gtc/',
    '/en/blog/': '/blog/',
    '/blog/all': '/blog/all/1/',
    '/blog/all/': '/blog/all/1/',
    '/en/blog/all/': '/blog/all/1/',
    '/en/blog/all/1/': '/blog/all/1/',
    '/ru/blog/all': '/ru/blog/all/1/',
    '/ru/blog/all/': '/ru/blog/all/1/',
    '/fr/blog/all': '/fr/blog/all/1/',
    '/fr/blog/all/': '/fr/blog/all/1/',
    '/de/blog/all': '/de/blog/all/1/',
    '/de/blog/all/': '/de/blog/all/1/',
    '/en/ai-medical-scribe/': '/ai-medical-scribe/',
    '/en/hospital-documentation/': '/hospital-documentation/',
    '/en/clinical-compliance/': '/clinical-compliance/',
    '/en/blog/adopt-ai-paris-november-2025/': '/blog/adopt-ai-paris-november-2025/',
    '/en/blog/buzz-esante-feature-april-2026/': '/blog/buzz-esante-feature-april-2026/',
    '/en/blog/chu-bordeaux-december-2025/': '/blog/chu-bordeaux-december-2025/',
    '/en/blog/docnote-gdpr-nfadp-compliance/': '/blog/docnote-gdpr-nfadp-compliance/',
    '/en/blog/docnote-les-echos-european-ai-health/': '/blog/docnote-les-echos-european-ai-health/',
    '/en/blog/docnote-mediway-integration/': '/blog/docnote-mediway-integration/',
    '/en/blog/docnote-radiology-mode/': '/blog/docnote-radiology-mode/',
    '/en/blog/ecc-st-gallen-december-2025/': '/blog/ecc-st-gallen-december-2025/',
    '/en/blog/fongit-startup-support-march-2026/': '/blog/fongit-startup-support-march-2026/',
    '/en/blog/future-of-ai-medical-documentation/': '/blog/future-of-ai-medical-documentation/',
    '/en/blog/hipaa-compliance-ai-tools/': '/blog/hipaa-compliance-ai-tools/',
    '/en/blog/less-time-documenting-ai-more-care/': '/blog/less-time-documenting-ai-more-care/',
    '/en/blog/medintechs-paris-march-2026/': '/blog/medintechs-paris-march-2026/',
    '/en/blog/reducing-physician-burnout/': '/blog/reducing-physician-burnout/',
    '/en/blog/scs-lausanne-may-2025/': '/blog/scs-lausanne-may-2025/',
    '/en/blog/scs-lucerne-june-2026/': '/blog/scs-lucerne-june-2026/',
    '/en/blog/sgaim-presentation-april-2025/': '/blog/sgaim-presentation-april-2025/',
    '/en/blog/soap-notes-best-practices/': '/blog/soap-notes-best-practices/',
  },
});
