import { defineCollection, z } from 'astro:content';

const pagesCollection = defineCollection({
  type: 'data',
  schema: z.object({
    nav: z.object({
      tutorial: z.string(),
      pricing: z.string(),
      blog: z.string(),
      team: z.string(),
      survey: z.string(),
      patient: z.string(),
      joinUs: z.string(),
      demo: z.string(),
      webApp: z.string(),
      appStore: z.string(),
      googlePlay: z.string(),
      /** Pillars + use-case landings */
      solutions: z.string().optional(),
      /** Specialty landings */
      specialties: z.string().optional(),
      /** Overflow ("More") menu trigger */
      more: z.string().optional(),
    }),
    hero: z.object({
      badge: z.string(),
      title: z.string(),
      titleHighlight: z.string(),
      subtitle: z.string(),
      cta: z.string(),
      ctaSecondary: z.string(),
      founders: z.string(),
      foundersRole: z.string(),
      trustedBy: z.string(),
    }),
    soapDemo: z.object({
      consultations: z.string(),
      patients: z.string(),
      templates: z.string(),
      settings: z.string(),
      consultationTitle: z.string(),
      consultationDate: z.string(),
      recording: z.string(),
      soapNoteGenerated: z.string(),
      soapNote: z.string(),
      savedToEHR: z.string(),
      justNow: z.string(),
      patientId: z.string(),
      generalPractice: z.string(),
      liveTranscript: z.string(),
      soapS: z.string(),
      soapO: z.string(),
      soapA: z.string(),
      soapP: z.string(),
      phoneSoapS: z.string(),
      phoneSoapO: z.string(),
      phoneSoapA: z.string(),
      phoneSoapP: z.string(),
    }),
    stats: z.object({
      timeSaved: z.string(),
      timeSavedValue: z.string(),
      timeSavedSuffix: z.string(),
      timeSavedDesc: z.string(),
      accuracy: z.string(),
      accuracyValue: z.string(),
      accuracyDesc: z.string(),
      doctors: z.string(),
      doctorsValue: z.string(),
      doctorsDesc: z.string(),
    }),
    features: z.object({
      badge: z.string(),
      title: z.string(),
      subtitle: z.string(),
      recording: z.object({
        title: z.string(),
        description: z.string(),
        animStatus: z.string(),
        animWords: z.array(z.string()),
      }),
      transcription: z.object({
        title: z.string(), description: z.string(),
        animLine1: z.string(), animLine2Pre: z.string(),
        animWrong1: z.string(), animRight1: z.string(), animLine2Post: z.string(),
        animLine3Pre: z.string(), animWrong2: z.string(), animRight2: z.string(), animLine3Post: z.string(),
      }),
      summaries: z.object({
        title: z.string(), description: z.string(),
        animTitle: z.string(), animSection1: z.string(), animSection2: z.string(), animSection3: z.string(),
      }),
      integration: z.object({
        title: z.string(),
        description: z.string(),
        animTitle: z.string(),
        animPatient: z.string(),
        animDob: z.string(),
        animNotes: z.string(),
        animNoReport: z.string(),
      }),
      security: z.object({
        title: z.string(), description: z.string(),
        animLabel1: z.string(), animLabel2: z.string(), animLabel3: z.string(), animLabel4: z.string(),
        animValue1: z.string(), animValue2: z.string(), animValue3: z.string(), animValue4: z.string(),
        animNoReport: z.string(),
      }),
      languages: z.object({ title: z.string(), description: z.string() }),
    }),
    specificities: z.object({
      badge: z.string(),
      title: z.string(),
      subtitle: z.string(),
      impactLabel: z.string(),
      stageLabel: z.string(),
      coding: z.object({
        title: z.string(),
        impact: z.string(),
        description: z.string(),
        descriptionCh: z.string(),
        descriptionRow: z.string(),
        stageLabel: z.string(),
        line1Pre: z.string(),
        line1Mark: z.string(),
        line1Post: z.string(),
        line2Pre: z.string(),
        line2Mark: z.string(),
        line2Post: z.string(),
        line3Pre: z.string(),
        line3Mark: z.string(),
        line3Post: z.string(),
      }),
      tardoc: z.object({
        title: z.string(),
        impact: z.string(),
        description: z.string(),
        stageLabel: z.string(),
        shortDictation: z.string(),
        expandLabel: z.string(),
        fullDescription: z.string(),
      }),
      ehr: z.object({
        title: z.string(),
        impact: z.string(),
        description: z.string(),
        stageLabel: z.string(),
        docReady: z.string(),
        docMeta: z.string(),
      }),
      templates: z.object({
        title: z.string(),
        impact: z.string(),
        description: z.string(),
        stageLabel: z.string(),
        fileName: z.string(),
        dropHint: z.string(),
        letterhead: z.string(),
        letterBody: z.string(),
      }),
      context: z.object({
        title: z.string(),
        impact: z.string(),
        description: z.string(),
        stageLabel: z.string(),
        chip1: z.string(),
        chip2: z.string(),
        chip3: z.string(),
        meterLabel: z.string(),
        meterNote: z.string(),
      }),
      hospital: z.object({
        title: z.string(),
        impact: z.string(),
        description: z.string(),
        stageLabel: z.string(),
        type1Title: z.string(),
        type1Sub: z.string(),
        type2Title: z.string(),
        type2Sub: z.string(),
        type3Title: z.string(),
        type3Sub: z.string(),
      }),
      sync: z.object({
        title: z.string(),
        impact: z.string(),
        description: z.string(),
        stageLabel: z.string(),
        phone: z.string(),
        recording: z.string(),
        desktop: z.string(),
        sameDraft: z.string(),
      }),
      dayHospital: z.object({
        title: z.string(),
        impact: z.string(),
        description: z.string(),
        stageLabel: z.string(),
        mergeResult: z.string(),
      }),
    }),
    valueProp: z.object({
      title: z.string(),
      subtitle: z.string(),
      card1: z.object({ title: z.string(), description: z.string() }),
      card2: z.object({ title: z.string(), description: z.string() }),
      card3: z.object({ title: z.string(), description: z.string() }),
    }),
    compliance: z.object({
      badge: z.string(),
      title: z.string(),
      subtitle: z.string(),
      cardTitle: z.string(),
      cardDescription: z.string(),
      protocolTitle: z.string(),
      protocolEncryption: z.string(),
      protocolRetention: z.string(),
      protocolRbac: z.string(),
      protocolAudit: z.string(),
      swiss: z.object({ title: z.string(), description: z.string() }),
      hipaa: z.object({ title: z.string(), description: z.string() }),
      iso: z.object({ title: z.string(), description: z.string() }),
    }),
    faq: z.object({
      title: z.string(),
      subtitle: z.string(),
      contactUs: z.string(),
      q1: z.string(), a1: z.string(),
      q2: z.string(), a2: z.string(), a2Ch: z.string(), a2Row: z.string(),
      q3: z.string(), a3: z.string(), a3Ch: z.string(), a3Row: z.string(),
      q4: z.string(), a4: z.string(),
      q5: z.string(), a5: z.string(),
      q6: z.string(), a6: z.string(),
      q7: z.string(), a7: z.string(),
      q8: z.string(), a8: z.string(), a8Ch: z.string(), a8Row: z.string(),
      q9: z.string(), a9: z.string(),
    }),
    specialties: z.object({
      title: z.string(),
      subtitle: z.string(),
      items: z.array(z.string()),
      countLabel: z.string().optional(),
      familiesCta: z.string().optional(),
    }),
    testimonials: z.object({
      badge: z.string(),
      title: z.string(),
      subtitle: z.string(),
      items: z
        .array(
          z.object({
            quote: z.string(),
            author: z.string(),
            role: z.string(),
            image: z.string(),
          })
        )
        .optional(),
      quote1: z.string(),
      author1: z.string(),
      role1: z.string(),
      quote2: z.string(),
      author2: z.string(),
      role2: z.string(),
      quote3: z.string(),
      author3: z.string(),
      role3: z.string(),
    }),
    cta: z.object({
      title: z.string(),
      subtitle: z.string(),
      button: z.string(),
      noCard: z.string(),
    }),
    footer: z.object({
      description: z.string(),
      product: z.string(),
      company: z.string(),
      legal: z.string(),
      features: z.string(),
      pricing: z.string(),
      integrations: z.string(),
      about: z.string(),
      blog: z.string(),
      careers: z.string(),
      contact: z.string(),
      privacy: z.string(),
      terms: z.string(),
      gtc: z.string(),
      gdpr: z.string(),
      rights: z.string(),
    }),
    pricing: z.object({
      title: z.string(),
      subtitle: z.string(),
      monthly: z.string(),
      yearly: z.string(),
      save: z.string(),
      perMonth: z.string(),
      getStarted: z.string(),
      subscription: z.string(),
      freeTrial: z.string(),
      professional: z.object({
        name: z.string(),
        price: z.string(),
        monthlyPrice: z.string(),
        description: z.string(),
        features: z.array(z.string()),
        popular: z.string(),
      }),
      enterprise: z.object({
        name: z.string(),
        price: z.string(),
        description: z.string(),
        features: z.array(z.string()),
        contact: z.string(),
      }),
      compare: z
        .object({
          title: z.string(),
          subtitle: z.string().optional(),
          feature: z.string(),
          pro: z.string(),
          enterprise: z.string(),
          yes: z.string(),
          no: z.string(),
          custom: z.string(),
          rows: z.array(
            z.object({
              label: z.string(),
              pro: z.enum(['yes', 'no', 'custom']),
              enterprise: z.enum(['yes', 'no', 'custom']),
            })
          ),
        })
        .optional(),
      faq: z.object({
        title: z.string(),
        q1: z.string(),
        a1: z.string(),
        q2: z.string(),
        a2: z.string(),
        q3: z.string(),
        a3: z.string(),
        q4: z.string(),
        a4: z.string(),
        q5: z.string().optional(),
        a5: z.string().optional(),
        q6: z.string().optional(),
        a6: z.string().optional(),
        q7: z.string().optional(),
        a7: z.string().optional(),
        q8: z.string().optional(),
        a8: z.string().optional(),
        q9: z.string().optional(),
        a9: z.string().optional(),
        q10: z.string().optional(),
        a10: z.string().optional(),
      }),
    }),
    blog: z.object({
      title: z.string(),
      subtitle: z.string(),
      readMore: z.string(),
      backToBlog: z.string(),
      recentPosts: z.string(),
      minRead: z.string(),
      shareArticle: z.string(),
      articles: z.string().optional(),
      prev: z.string().optional(),
      next: z.string().optional(),
      viewAllArticles: z.string().optional(),
      pageLabel: z.string().optional(),
      onThisPage: z.string().optional(),
      writtenBy: z.string().optional(),
      share: z.string().optional(),
      relatedArticles: z.string().optional(),
      createdOn: z.string().optional(),
      categories: z.object({
        all: z.string(),
        news: z.string(),
        ai: z.string(),
        documentation: z.string(),
        practice: z.string(),
      }),
    }),
    team: z.object({
      aboutUs: z.string(),
      title: z.string(),
      subtitle: z.string(),
      intro: z.string().optional(),
      story: z.string().optional(),
      highlightsTitle: z.string().optional(),
      highlightsLead: z.string().optional(),
      highlights: z
        .array(
          z.object({
            title: z.string(),
            body: z.string(),
          })
        )
        .optional(),
      highlightsClosing: z.string().optional(),
      members: z.object({
        vincentTan: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
        aliceGilson: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
        mathiasGilson: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
        jeremyYvinec: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
        hugoRoussel: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
        ericWei: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
        nedimAmer: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
        valeryDemunck: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
        julietteKristanek: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
      }),
    }),
    tutorial: z.object({
      title: z.string(),
      subtitle: z.string(),
      step1: z.object({
        title: z.string(),
        description: z.string(),
        ios: z.string(),
        android: z.string(),
      }),
      step2: z.object({
        title: z.string(),
        description: z.string(),
        trialInfo: z.string(),
      }),
      step3: z.object({
        title: z.string(),
        description: z.string(),
        chooseModel: z.string(),
        models: z.object({
          dictation: z.object({
            title: z.string(),
            description: z.string(),
          }),
          general: z.object({
            title: z.string(),
            description: z.string(),
          }),
          specialist: z.object({
            title: z.string(),
            description: z.string(),
          }),
          operative: z.object({
            title: z.string(),
            description: z.string(),
          }),
          followUp: z.object({
            title: z.string(),
            description: z.string(),
          }),
          discharge: z.object({
            title: z.string(),
            description: z.string(),
          }),
        }),
      }),
      step4: z.object({
        title: z.string(),
        description: z.string(),
      }).optional(),
      step5: z.object({
        title: z.string(),
        description: z.string(),
      }).optional(),
      cta: z.object({
        title: z.string(),
        subtitle: z.string(),
        appStore: z.string(),
        googlePlay: z.string(),
        webApp: z.string(),
        getDemo: z.string(),
      }),
    }),
    contact: z.object({
      title: z.string(),
      subtitle: z.string(),
      bookDemo: z.string(),
      emailLabel: z.string(),
      phoneLabel: z.string(),
      locationLabel: z.string(),
      switzerland: z.string(),
      france: z.string(),
      vincentName: z.string(),
      aliceName: z.string(),
      vincentRole: z.string().optional(),
      aliceRole: z.string().optional(),
      vincentFocus: z.string().optional(),
      aliceFocus: z.string().optional(),
      vincentCity: z.string().optional(),
      aliceCity: z.string().optional(),
      writeEmail: z.string().optional(),
      callPhone: z.string().optional(),
      hoursLabel: z.string().optional(),
      hoursValue: z.string().optional(),
      responseLabel: z.string().optional(),
      responseValue: z.string().optional(),
      companyLabel: z.string().optional(),
      companyValue: z.string().optional(),
      generalEmailLabel: z.string().optional(),
      generalEmail: z.string().optional(),
      hostingNote: z.string().optional(),
    }),
  }),
});

const blogCollection = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    excerpt: z.string(),
    category: z.enum(['ai', 'documentation', 'practice', 'news']),
    author: z.string(),
    authorRole: z.string(),
    authorImage: z.string(),
    image: z.string(),
    imagePosition: z.string().optional(),
    fullImage: z.boolean().optional(),
    date: z.string(),
    readTime: z.number(),
  }),
});

export const collections = {
  pages: pagesCollection,
  blog: blogCollection,
};
