import { defineCollection, z } from 'astro:content';

const pagesCollection = defineCollection({
  type: 'data',
  schema: z.object({
    nav: z.object({
      home: z.string(),
      pricing: z.string(),
      blog: z.string(),
      team: z.string(),
      signIn: z.string(),
      getStarted: z.string(),
    }),
    hero: z.object({
      badge: z.string(),
      title: z.string(),
      titleHighlight: z.string(),
      subtitle: z.string(),
      cta: z.string(),
      ctaSecondary: z.string(),
      trustedBy: z.string(),
    }),
    stats: z.object({
      timeSaved: z.string(),
      timeSavedValue: z.string(),
      timeSavedDesc: z.string(),
      accuracy: z.string(),
      accuracyValue: z.string(),
      accuracyDesc: z.string(),
      doctors: z.string(),
      doctorsValue: z.string(),
      doctorsDesc: z.string(),
    }),
    features: z.object({
      title: z.string(),
      subtitle: z.string(),
      recording: z.object({ title: z.string(), description: z.string() }),
      transcription: z.object({ title: z.string(), description: z.string() }),
      summaries: z.object({ title: z.string(), description: z.string() }),
      integration: z.object({ title: z.string(), description: z.string() }),
      security: z.object({ title: z.string(), description: z.string() }),
      languages: z.object({ title: z.string(), description: z.string() }),
    }),
    specialties: z.object({
      title: z.string(),
      subtitle: z.string(),
    }),
    testimonials: z.object({
      title: z.string(),
      subtitle: z.string(),
    }),
    cta: z.object({
      title: z.string(),
      subtitle: z.string(),
      button: z.string(),
      noCard: z.string(),
    }),
    footer: z.object({
      description: z.string(),
      product: z.string(),
      company: z.string(),
      legal: z.string(),
      features: z.string(),
      pricing: z.string(),
      integrations: z.string(),
      about: z.string(),
      blog: z.string(),
      careers: z.string(),
      contact: z.string(),
      privacy: z.string(),
      terms: z.string(),
      gdpr: z.string(),
      rights: z.string(),
    }),
    pricing: z.object({
      title: z.string(),
      subtitle: z.string(),
      monthly: z.string(),
      yearly: z.string(),
      save: z.string(),
      perMonth: z.string(),
      getStarted: z.string(),
      starter: z.object({
        name: z.string(),
        price: z.string(),
        description: z.string(),
        features: z.array(z.string()),
      }),
      professional: z.object({
        name: z.string(),
        price: z.string(),
        description: z.string(),
        features: z.array(z.string()),
        popular: z.string(),
      }),
      enterprise: z.object({
        name: z.string(),
        price: z.string(),
        description: z.string(),
        features: z.array(z.string()),
        contact: z.string(),
      }),
      faq: z.object({
        title: z.string(),
        q1: z.string(),
        a1: z.string(),
        q2: z.string(),
        a2: z.string(),
        q3: z.string(),
        a3: z.string(),
        q4: z.string(),
        a4: z.string(),
      }),
    }),
    blog: z.object({
      title: z.string(),
      subtitle: z.string(),
      readMore: z.string(),
      backToBlog: z.string(),
      recentPosts: z.string(),
      minRead: z.string(),
      shareArticle: z.string(),
      categories: z.object({
        all: z.string(),
        ai: z.string(),
        documentation: z.string(),
        practice: z.string(),
      }),
    }),
    team: z.object({
      title: z.string(),
      subtitle: z.string(),
      members: z.object({
        vincentTan: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
        aliceGilson: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
        mathiasGilson: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
        jeremyYvinec: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
        hugoRoussel: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
        ericWei: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
      }),
    }),
  }),
});

const blogCollection = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    excerpt: z.string(),
    category: z.enum(['ai', 'documentation', 'practice']),
    author: z.string(),
    authorRole: z.string(),
    authorImage: z.string(),
    image: z.string(),
    date: z.string(),
    readTime: z.number(),
  }),
});

export const collections = {
  pages: pagesCollection,
  blog: blogCollection,
};
