import { defineCollection, z } from 'astro:content';

const pagesCollection = defineCollection({
  type: 'data',
  schema: z.object({
    nav: z.object({
      tutorial: z.string(),
      pricing: z.string(),
      blog: z.string(),
      team: z.string(),
      demo: z.string(),
      webApp: z.string(),
      appStore: z.string(),
      googlePlay: z.string(),
    }),
    hero: z.object({
      badge: z.string(),
      title: z.string(),
      titleHighlight: z.string(),
      subtitle: z.string(),
      cta: z.string(),
      ctaSecondary: z.string(),
      trustedBy: z.string(),
    }),
    stats: z.object({
      timeSaved: z.string(),
      timeSavedValue: z.string(),
      timeSavedDesc: z.string(),
      accuracy: z.string(),
      accuracyValue: z.string(),
      accuracyDesc: z.string(),
      doctors: z.string(),
      doctorsValue: z.string(),
      doctorsDesc: z.string(),
    }),
    features: z.object({
      title: z.string(),
      subtitle: z.string(),
      recording: z.object({ title: z.string(), description: z.string() }),
      transcription: z.object({ title: z.string(), description: z.string() }),
      summaries: z.object({ title: z.string(), description: z.string() }),
      integration: z.object({ title: z.string(), description: z.string() }),
      security: z.object({ title: z.string(), description: z.string() }),
      languages: z.object({ title: z.string(), description: z.string() }),
    }),
    valueProp: z.object({
      title: z.string(),
      subtitle: z.string(),
      card1: z.object({ title: z.string(), description: z.string() }),
      card2: z.object({ title: z.string(), description: z.string() }),
      card3: z.object({ title: z.string(), description: z.string() }),
    }),
    compliance: z.object({
      title: z.string(),
      subtitle: z.string(),
      swiss: z.object({ title: z.string(), description: z.string() }),
      hipaa: z.object({ title: z.string(), description: z.string() }),
      iso: z.object({ title: z.string(), description: z.string() }),
    }),
    faq: z.object({
      title: z.string(),
      subtitle: z.string(),
      contactUs: z.string(),
      q1: z.string(),
      a1: z.string(),
      q2: z.string(),
      a2: z.string(),
      q3: z.string(),
      a3: z.string(),
      q4: z.string(),
      a4: z.string(),
      q5: z.string(),
      a5: z.string(),
      q6: z.string(),
      a6: z.string(),
    }),
    specialties: z.object({
      title: z.string(),
      subtitle: z.string(),
    }),
    testimonials: z.object({
      title: z.string(),
      subtitle: z.string(),
    }),
    cta: z.object({
      title: z.string(),
      subtitle: z.string(),
      button: z.string(),
      noCard: z.string(),
    }),
    footer: z.object({
      description: z.string(),
      product: z.string(),
      company: z.string(),
      legal: z.string(),
      features: z.string(),
      pricing: z.string(),
      integrations: z.string(),
      about: z.string(),
      blog: z.string(),
      careers: z.string(),
      contact: z.string(),
      privacy: z.string(),
      terms: z.string(),
      gdpr: z.string(),
      rights: z.string(),
    }),
    pricing: z.object({
      title: z.string(),
      subtitle: z.string(),
      monthly: z.string(),
      yearly: z.string(),
      save: z.string(),
      perMonth: z.string(),
      getStarted: z.string(),
      subscription: z.string(),
      professional: z.object({
        name: z.string(),
        price: z.string(),
        monthlyPrice: z.string(),
        description: z.string(),
        features: z.array(z.string()),
        popular: z.string(),
      }),
      enterprise: z.object({
        name: z.string(),
        price: z.string(),
        description: z.string(),
        features: z.array(z.string()),
        contact: z.string(),
      }),
      faq: z.object({
        title: z.string(),
        q1: z.string(),
        a1: z.string(),
        q2: z.string(),
        a2: z.string(),
        q3: z.string(),
        a3: z.string(),
        q4: z.string(),
        a4: z.string(),
      }),
    }),
    blog: z.object({
      title: z.string(),
      subtitle: z.string(),
      readMore: z.string(),
      backToBlog: z.string(),
      recentPosts: z.string(),
      minRead: z.string(),
      shareArticle: z.string(),
      categories: z.object({
        all: z.string(),
        news: z.string(),
        ai: z.string(),
        documentation: z.string(),
        practice: z.string(),
      }),
    }),
    team: z.object({
      title: z.string(),
      subtitle: z.string(),
      members: z.object({
        vincentTan: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
        aliceGilson: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
        mathiasGilson: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
        jeremyYvinec: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
        hugoRoussel: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
        ericWei: z.object({
          name: z.string(),
          role: z.string(),
          bio: z.string(),
        }),
      }),
    }),
    tutorial: z.object({
      title: z.string(),
      subtitle: z.string(),
      step1: z.object({
        title: z.string(),
        description: z.string(),
        ios: z.string(),
        android: z.string(),
      }),
      step2: z.object({
        title: z.string(),
        description: z.string(),
      }),
      step3: z.object({
        title: z.string(),
        description: z.string(),
        chooseModel: z.string(),
        models: z.object({
          dictation: z.object({
            title: z.string(),
            description: z.string(),
          }),
          general: z.object({
            title: z.string(),
            description: z.string(),
          }),
          specialist: z.object({
            title: z.string(),
            description: z.string(),
          }),
          operative: z.object({
            title: z.string(),
            description: z.string(),
          }),
          followUp: z.object({
            title: z.string(),
            description: z.string(),
          }),
          discharge: z.object({
            title: z.string(),
            description: z.string(),
          }),
        }),
      }),
      cta: z.object({
        title: z.string(),
        subtitle: z.string(),
        appStore: z.string(),
        googlePlay: z.string(),
        webApp: z.string(),
        getDemo: z.string(),
      }),
    }),
    contact: z.object({
      title: z.string(),
      subtitle: z.string(),
      emailLabel: z.string(),
      phoneLabel: z.string(),
      locationLabel: z.string(),
      switzerland: z.string(),
      france: z.string(),
    }),
  }),
});

const blogCollection = defineCollection({
  type: 'content',
  schema: z.object({
    title: z.string(),
    excerpt: z.string(),
    category: z.enum(['ai', 'documentation', 'practice', 'news']),
    author: z.string(),
    authorRole: z.string(),
    authorImage: z.string(),
    image: z.string(),
    date: z.string(),
    readTime: z.number(),
  }),
});

export const collections = {
  pages: pagesCollection,
  blog: blogCollection,
};
